name: Generate Pizza Data

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12-slim
    steps:
      - uses: "actions/checkout@v4"
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: uv pip install -r requirements.txt --system
      - name: Generate pizza data
        run: |
          cd scripts
          python create_pizza_data.py
          mv raw_pizza_sales.csv ../seeds/raw_pizza_sales.csv
          mv ingredients.csv ../seeds/ingredients.csv
